version: "3.8"
services:
  db:
    image: mysql:8.3.0
    container_name: 'game-app-mysql'
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    command: [ 'mysqld', '--character-set-server=utf8mb4' ,'--collation-server=utf8mb4_unicode_ci' ]
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gameapp_db
      MYSQL_PASSWORD: password

volumes:
  dbdata: